# Generated by Django 2.2.5 on 2019-09-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='color',
        ),
        migrations.AddField(
            model_name='sort',
            name='image',
            field=models.ImageField(blank=True, upload_to='SortImg', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='code',
            field=models.CharField(max_length=10, verbose_name='规格'),
        ),
    ]
